MODEL:
  architecture:  "TSViTcls"
  img_res: 24
  max_seq_len: 60  #
  num_channels: 11
  num_features: 16
  num_classes: 19
  ignore_background: True
  dropout: 0.
  patch_size: 3
  dim: 64
  temporal_depth: 8
  spatial_depth: 4
  heads: 4
  pool: 'cls'
  dim_head: 32
  emb_dropout: 0.
  scale_dim: 4

DATASETS:
  train:
    dataset: 'PASTIS24_fold1'
    label_map:
    max_seq_len: 60
    batch_size: 32
    extra_data:
    num_workers: 1

  eval:
    dataset: 'PASTIS24_fold1'
    label_map:
    max_seq_len: 60
    batch_size: 32
    extra_data:
    num_workers: 1

SOLVER:
  num_epochs: 100
  num_warmup_epochs: 10
  steps: (0, 80000)
  loss_function: focal_loss
  class_weights:
  lr_scheduler:
  lr_base: 1e-3
  lr_min: 5e-6
  lr_start: 1e-8
  num_cycles: 1
  reset_lr: True   # resets lr to base value when loading pretrained model
  weight_decay: 0.00
  gamma: 1.0
  alpha:

CHECKPOINT:
  load_from_checkpoint:
  partial_restore: False
  save_path: 'models/saved_models/PASTIS24/TSViT-S_cls'
  train_metrics_steps: 1138
  eval_steps: 1138
  save_steps: 113600
 